# Name des Workflows, der im "Actions"-Tab angezeigt wird
name: Create Release with Executable JAR

# Trigger: Dieser Workflow startet, wenn ein neuer Tag erstellt wird,
# der mit "v" beginnt (z.B. v1.1.0, v1.2.3)
on:
  push:
    tags:
      - 'v*.*.*'

# Definiert die Aufgaben (Jobs), die ausgef체hrt werden sollen
jobs:
  build-and-release:
    # Der Job l채uft auf einem von GitHub bereitgestellten Server mit Ubuntu
    runs-on: ubuntu-latest

    # Die einzelnen Schritte des Jobs
    steps:
      # 1. Schritt: Code aus dem Repository auschecken
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Schritt: Java Development Kit (JDK) 11 einrichten
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Schritt: Projekt mit Maven bauen (erstellt die .jar-Datei)
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 4. Schritt: Release erstellen und die JAR-Datei hochladen
      - name: Create Release and Upload JAR
        uses: softprops/action-gh-release@v1
        with:
          # Diese Zeile sorgt daf체r, dass alle .jar-Dateien aus dem target-Ordner
          # an das Release angeh채ngt werden.
          files: target/*.jar
